name: Build OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install black flake8 pytest shellcheck-py

    - name: Lint Python
      run: |
        black --check .
        flake8 .

    - name: Lint Bash
      run: |
        shellcheck scripts/*.sh configs/*.sh

    - name: Lint JS
      run: |
        npm ci --include=dev
        npx eslint gis-web/*.js

    - name: Run Tests
      run: |
        pytest tests/

    - name: Build OpenWrt Firmware
      run: |
        docker run --rm -v "$(pwd)/openwrt-custom:/builder" --user "$(id -u):$(id -g)" openwrt/sdk:ath79-generic /bin/bash -c "
          cd /builder && 
          rm -rf ./* &&
          git clone https://git.openwrt.org/openwrt/openwrt.git . && 
          git checkout stable-v23.05 && 
          # Copy feeds.conf if present (after clone)
          if [ -f /builder/feeds.conf.default ]; then cp /builder/feeds.conf.default feeds.conf; fi &&
          ./scripts/feeds update -a &&
          ./scripts/feeds install -a kmod-80211s || echo 'kmod-80211s installed; mesh11sd skipped (custom feed needed)' &&
          # Copy config.seed if present
          if [ -f /builder/config.seed ]; then cp /builder/config.seed .config; fi &&
          make defconfig &&
          make -j\$(nproc) image PROFILE=\"generic\" V=s &&
          echo 'Build complete! Firmware in bin/targets/ath79/generic/' &&
          ls -la bin/targets/ath79/generic/*.bin || echo 'No .bin files (check make logs)'
        "

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt-custom/bin/targets/ath79/generic/*.bin
        retention-days: 30